-- dink_tokens — per-user Dink config tokens.
--
-- This table is OWNED/CREATED by the Discord bot (volition-discord-bot:
-- db/dinkTokens.js). It is reproduced here for reference because the SITE and the
-- dink-proxy both read/write it:
--   • Site  (src/lib/server/dinkTokens.ts): mint / rotate / revoke a user's token,
--            and build their `${PROXY_BASE_URL}/config/<token>` link.
--   • Proxy (dink-proxy/src/index.js): validates incoming tokens against the active
--            (revoked_at IS NULL) rows here, unioned with its VALID_TOKENS secret.
--
-- A user has at most ONE active token at a time (keyed by discord_id); rotating
-- revokes the old row and inserts a new one. Run this only if the table doesn't
-- already exist in the project.

create table if not exists dink_tokens (
	id bigint generated by default as identity primary key,
	token text not null unique,
	discord_id text not null,
	created_at timestamptz not null default now(),
	revoked_at timestamptz
);

-- Proxy validation reads active tokens; site reads a user's active token by discord_id.
create index if not exists dink_tokens_active_idx on dink_tokens (token) where revoked_at is null;
create index if not exists dink_tokens_discord_active_idx on dink_tokens (discord_id) where revoked_at is null;
